# Start from the latest golang base image
FROM golang:1.16 as builder

# Set the Current Working Directory inside the container
RUN mkdir -p /go/src/search_server
WORKDIR /go/src/search_server

# Copy data to working dir
COPY . .

# Install dependencies
RUN go mod download

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -v -a -installsuffix cgo -o ./cmd/main ./cmd/main.go

######## Start a new stage from scratch #######
FROM alpine:latest

RUN apk --no-cache add tzdata zip ca-certificates

WORKDIR /go/src/search_server

# Copy the Pre-built binary file from the previous stage
COPY --from=builder /go/src/search_server .

# Command to run the executable
CMD ["./cmd/main"]